-- Scripts de criação da estrutura da aplicação Chronos Windows
USE [master]
CREATE DATABASE [chronos-windows];

GO

USE [chronos-windows];
CREATE TABLE cliente
(
	id INT NOT NULL IDENTITY,
	nome VARCHAR(100) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	endereco VARCHAR(100) NULL,
	numero_endereco VARCHAR(10) NULL,
	bairro VARCHAR(40) NULL,
	cidade VARCHAR(40) NULL,
	uf VARCHAR(2) NULL,
	sincronizar BIT NOT NULL,
	CONSTRAINT [PK_cliente] PRIMARY KEY CLUSTERED (id ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE produto
(
	id INT NOT NULL IDENTITY,
	nome VARCHAR(100) NOT NULL,
	preco DECIMAL(10,2) NOT NULL,
	sincronizar BIT NOT NULL,
	CONSTRAINT [PK_produto] PRIMARY KEY CLUSTERED (id ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
